### ISSUE TITLE
List all last saves on a Discord server

### ISSUE THREAD

**Issue by montyx00** [deesnow/SnakeBot#10]
**Description**
As a <Master> I cannot list the last saves of all the registered SnakeBot users on a DIscord server.

**Expected behavior**
I'd like to use the following command:
snk list all
Then I'd like to see the list of the last saves of every registered SnakeBot users on the current Discord server in the following format:

```----------------------------------------------
Eugene Wagner - Save 1 - 2019.05.25
----------------------------------------------
Katherine Sandoval - Save 2 - 2019.04.10
----------------------------------------------
Rose Spencer - Save 3 - 2019.02.17
----------------------------------------------```

**Comment by deesnow** [comment]
Because of the high number of guilds it is canceled. I will apply guild lvl commands instead
