### ISSUE TITLE
Cannot check diff w/o <Master> permission

### ISSUE THREAD

**Issue by montyx00** [deesnow/SnakeBot#9]
**Issue**
As user without <Master> permission I don't have right to check my progress based on any of my saves

**Solution**
Every user, with or without <Master> permission have to had the rights to check their saves. So the following command have to work for everyone:
snk now me savename

**Comment by deesnow** [comment]
Permission check removed from
snk list
snk now
commands, but still checked on
snk save
snk del_save (ds)

**Comment by deesnow** [comment]
Fixed in version 1.1
